package dev.repodoc;
import java.util.List;
public final class Cases {
  private Cases() {}
  public static final List<ReviewCase> ALL=List.of(
    new ReviewCase("tenant-leak","PR #184: Add record details endpoint","TypeScript","Multi-tenant Express API. req.user.tenantId contains the authenticated tenant.","+ router.get('/records/:id', async (req,res) => {\n+   const record = await db.records.findUnique({ where: { id: req.params.id } })\n+   if (!record) return res.sendStatus(404)\n+   return res.json(record)\n+ })",List.of(new ReviewCase.Option("bola","Object-level authorization is missing","critical"),new ReviewCase.Option("404","Returning 404 is always incorrect","low"),new ReviewCase.Option("validation","ID format is not validated before query","medium"),new ReviewCase.Option("async","Async route handlers should never be used","low")),List.of("bola","validation")),
    new ReviewCase("transfer-race","PR #251: Improve balance transfer","Java","Two concurrent requests can transfer funds from the same account.","+ if (account.balance() >= amount) {\n+   account.setBalance(account.balance() - amount);\n+   ledger.insert(transfer);\n+ }",List.of(new ReviewCase.Option("atomic","Balance check and update are not atomic","critical"),new ReviewCase.Option("decimal","Money should use a decimal/integer-safe representation","high"),new ReviewCase.Option("setter","Setters are always insecure","low"),new ReviewCase.Option("comment","The block needs an inline comment","low")),List.of("atomic","decimal")),
    new ReviewCase("react-effect","PR #319: Refresh search on filter change","TypeScript","React component fetches search results when filters change.","+ useEffect(() => {\n+   fetch(`/api/search?q=${query}`).then(r=>r.json()).then(setResults)\n+ }, [query, results])",List.of(new ReviewCase.Option("loop","Including results can create a request/render loop","high"),new ReviewCase.Option("stale","No cancellation/version guard for stale responses","medium"),new ReviewCase.Option("fetch","fetch() is deprecated","low"),new ReviewCase.Option("promise","Promises should never be used in React","low")),List.of("loop","stale")),
    new ReviewCase("webhook","PR #402: Process payment webhooks","Python","The provider retries webhook delivery until it receives 2xx.","+ @app.post('/webhook')\n+ def webhook(event: dict):\n+     charge_order(event['order_id'])\n+     return {'ok': True}",List.of(new ReviewCase.Option("idempotency","No idempotency protection against repeated delivery","critical"),new ReviewCase.Option("signature","No evidence of webhook signature verification","critical"),new ReviewCase.Option("typing","dict should never be used as a type","low"),new ReviewCase.Option("json","JSON responses are insecure","low")),List.of("idempotency","signature")),
    new ReviewCase("retry-storm","PR #448: Make vendor calls reliable","Python","Service calls an external API that sometimes returns 429/503.","+ for attempt in range(10):\n+     r = requests.get(URL)\n+     if r.ok: return r.json()",List.of(new ReviewCase.Option("timeout","Outbound request has no explicit timeout","high"),new ReviewCase.Option("backoff","Retry loop has no backoff/jitter or Retry-After handling","high"),new ReviewCase.Option("attempts","Ten attempts is universally correct","low"),new ReviewCase.Option("json","Calling json() is always unsafe","low")),List.of("timeout","backoff"))
  );
  public static ReviewCase byId(String id){return ALL.stream().filter(c->c.id().equals(id)).findFirst().orElse(null);}
}
